Delete mailer customizations
OpenSourcePolitics/decidim-nanterre pull request #1
Opened 2021-10-01 14:04 UTC by paulinebessoles

This PR aims to delete private user invitation mailer.

Old mailer:
![image](https://user-images.githubusercontent.com/52420208/135633266-0ee6d6cb-15c0-4a40-9912-b694d36f71f8.png)

2021-10-01 14:55 UTC, MoretS approved these changes

2021-10-04 09:23 UTC, armandfardeau requested changes
Hello @paulinebessoles, Could you explain why you have deleted the initializer and the migration?

2021-10-04 10:54 UTC, paulinebessoles commented
Hi @armandfardeau, the idea was to come back to the original behaviour for private users invitations. 
The initializer is not up to date with the client's use case. 
Concerning the migration, the address for projects is not a feature available in the core, so the idea was to disable it (and it caused several problems in local). Do you think I should add it again?

2021-10-04 15:14 UTC, merged

2021-10-04 17:19 UTC, armandfardeau commented
I will have a look and fix everything. Don't worry.